name: Compilation Testing
on:
  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.h'
    - '**compile-examples.yml'
  pull_request:
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.h'
    - '**compile-examples.yml'
jobs:
  build:
    name: ${{ matrix.arduino-boards-fqbn }} ${{ matrix.log-options }} ${{ matrix.other-options }}
    runs-on: ubuntu-latest
    
    env:
      REQUIRED_LIBRARIES: FastLED
    strategy:
      matrix:
        arduino-boards-fqbn:
          - esp8266:esp8266:huzzah
        platform-url:
          - https://arduino.esp8266.com/stable/package_esp8266com_index.json
          
        log-options: [-DDEBUG]

      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@v3
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          platform-url: ${{ matrix.platform-url }}
          required-libraries: ${{ env.REQUIRED_LIBRARIES }}
          build-properties: '{ "All": "${{ matrix.log-options }} ${{ matrix.other-options }}" }'

      - name: Doxygen Build
        uses: langroodi/doxygenize@v1.3
        with:
          doxygenconf: './docs/Doxyfile'
          htmloutput: './docs/'
          ghpagesbranch: 'gh-pages'
          ghpagesdir: './docs/'
