name: Linting, Compilation Testing, Documentation Build
on:
  push: # see: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.h'
    - '**.sh'
    - '**compile-examples.yml'
    - '**Doxyfile'
    - 'library.properties'
    - 'library.json'
  pull_request:
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.h'
    - '**.sh'
    - '**compile-examples.yml'
    - '**Doxyfile'
    - 'library.properties'
    - 'library.json'
jobs:
  build:
    name: "Linting, Compilation Testing, Documentation Build"
    runs-on: ubuntu-latest
    
    env:
      REQUIRED_LIBRARIES: FastLED
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
     
      - name: Arduino Linter
        uses: arduino/arduino-lint-action@v1
        with:
          library-manager: submit
          compliance: strict
          recursive: true
          verbose: true
          report-file: ./extras/lint_report.json

#      - name: Compile all examples (ESP8266)
#        uses: ArminJo/arduino-test-compile@v3
#        with:
#          arduino-board-fqbn: "esp8266:esp8266:d1_mini"
#          platform-url: "https://arduino.esp8266.com/stable/package_esp8266com_index.json"
#          required-libraries: ${{ env.REQUIRED_LIBRARIES }}
#      
#      - name: Compile all examples (ESP32)
#        uses: ArminJo/arduino-test-compile@v3
#        with:
#          arduino-board-fqbn: "esp32:esp32:nodemcu-32s"
#          platform-url: "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json"
#          required-libraries: ${{ env.REQUIRED_LIBRARIES }}


        #run: "ls -l && sudo chmod +x ./extras/doxygenerate.sh && sudo ./extras/doxygenerate.sh"
        #shell: bash

      - name: Doxygen Build        
        uses: langroodi/doxygenize@v1.3
        with:
          doxygenconf: './docs/Doxyfile'
          htmloutput: './docs/'
          ghpagesbranch: 'main'
          ghpagesdir: './docs/'
          
      - name: Clean Up Extras
        run: "sudo chmod +x ./extras/cleanup_ci.sh && sudo ./extras/cleanup_ci.sh"
        shell: bash
